import assert from 'node:assert/strict';
import { IDBFactory } from 'fake-indexeddb';
import { chromeFixture } from './fixtures/chrome.mjs';
const f = chromeFixture(); f.grants.add('https://canvas.example.test/*');
f.chrome.storage.local.data.enabledOrigins = ['https://canvas.example.test'];
globalThis.chrome = f.chrome; globalThis.indexedDB = new IDBFactory();
const { senderKind } = await import('../extension/background.mjs');
const own = { id: 'test-extension', url: 'chrome-extension://test-extension/options.html' };
const page = { id: 'test-extension', url: 'https://canvas.example.test/client', tab: { id: 1 } };
const enabled = ['https://canvas.example.test'];
assert.equal(senderKind(own, 'test-extension'), 'settings'); assert.equal(senderKind(page, 'test-extension', enabled), 'page');
for (const sender of [{ ...page, id: 'other' }, { ...page, url: 'https://unselected.example.test/client' }, { ...page, url: 'https://canvas.example.test.evil.test/client' }, { ...page, tab: undefined }]) assert.equal(senderKind(sender, 'test-extension', enabled), null);
const listener = f.chrome.runtime.onMessage.listeners[0], send = (message, sender) => new Promise(resolve => listener(message, sender, resolve));
for (const action of ['setSettings', 'setPreferences', 'getSettings', 'probe', 'exportTranslations', 'importTranslations', 'getCacheStats', 'getPersonalTranslation', 'setPersonalTranslation', 'removePersonalTranslation', 'clearCache', 'getPageContext', 'enableSites', 'disableSites']) assert.equal((await send({ action, payload: {} }, page)).ok, false, action);
assert.equal((await send({ action: 'setSettings', payload: { provider: 'openai', apiBase: 'https://api.example.test/v1', model: 'test-model', apiKey: 'TEST_ONLY_NOT_SECRET' } }, own)).ok, true);
const preferences = await send({ action: 'getPreferences' }, page); assert(preferences.ok);
assert(!Object.hasOwn(preferences.data, 'apiBase')); assert(!JSON.stringify(preferences).includes('TEST_ONLY_NOT_SECRET'));
f.grants.delete('https://canvas.example.test/*'); assert.equal((await send({ action: 'getPreferences' }, page)).ok, false);
console.log('Background: trusted settings, enabled origins, credential isolation, page operation restrictions, and permission revocation checks passed.');
